apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: public
  rules:
    - http:
        paths:
          - path: /vault
            pathType: Exact
            backend:
              service:
                name: sit-vault-ui
                port:
                  number: 80
