vault:
  global:
    namespace: vault
  ui:
    enabled: true
  server:
    standalone:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = true
          address = "[::]:8200"
        }
        storage "file" {
          path = "/vault/data"
        }
    dev:
      enabled: true
    enabled: true
    dataStorage:
      size: 2Gi
