apiVersion: v2
version: 0.0.1
name: argo-cd
dependencies:
  - name: argo-cd
    version: 5.53.4
    repository: https://argoproj.github.io/argo-helm
  - name: imagepullsecret-patcher
    version: 1.0.0
    repository: https://empathyco.github.io/helm-charts/
