vault:
  global:
    namespace: sit-vault
  ui:
    enabled: true
    serviceType: NodePort
    externalPort: 80
    targetPort: 8200
    serviceNodePort: 30001
  server:
    standalone:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = true
          address = "[::]:8200"
        }
        storage "file" {
          path = "/vault/data"
        }
    dev:
      enabled: true
    enabled: true
    dataStorage:
      size: 2Gi
