name: Build and publish Vault chart ghcr.io
on:
  push:
    paths:
      - vault/**
    branches:
      - main
env:
  HELM_EXPERIMENTAL_OCI: 1

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    name: publish gcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout repo

      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          version: 3.13.1

      - name: login to acr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/sorum-it --username ${{ github.repository_owner }} --password-stdin

      - name: save helm chart to local registry
        run: |
          helm package vault --dependency-update

      - name: Get chart version
        id: chart_version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' vault/Chart.yaml

      - name: publish chart to acr
        run: |
          helm push ./vault-${{ steps.chart_version.outputs.result }}.tgz oci://ghcr.io/sorum-it
