apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.argo-cd.repositories.k8s-cluster.name }}-repo-secret'
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: '{{ .Values.argo-cd.repositories.k8s-cluster.url }}'
  type: '{{ .Values.argo-cd.repositories.k8s-cluster.type }}'
  enableOci: 'true'
  username: <username>
  password: <password>
